name: 'Sops Binary Installer'
description: 'Install a specific version of the sops binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs: 
  version:
    description: 'Version of sops'
    required: true
    default: 'latest'
  token:
    description: 'Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.'
    default: ${{ secrets.GITHUB_TOKEN }}
outputs:
  sops-path:
    description: 'Path to the cached sops binary'
branding:
  icon: 'unlock'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
