name: 'Sops Binary Installer'
description: 'Install a specific version of the sops binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs: 
  version:
    description: 'Version of sops'
    required: true
    default: 'latest'
outputs:
  sops-path:
    description: 'Path to the cached sops binary'
branding:
  icon: 'unlock'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'dist/index.js'
  
