name: 'Run unit tests.'
on:
   pull_request:
      branches:
         - main
         - 'releases/*'
   push:
      branches:
         - main
         - 'releases/*'

jobs:
   build:
      strategy:
         matrix:
            os:
               - ubuntu-latest
               - ubuntu-24.04-arm
               - windows-latest
               - windows-11-arm
               - macos-latest
         fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

         - name: Install and test
           run: |
              npm install
              npm test
